import Head from "next/head";
import { ReactNode } from "react";
import Aside from "./aside";

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <Head>
        <title>Chat GPT Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full relative bg-gptgray h-screen'>
        <Aside />
        {children}
      </div>
    </>
  )
}